In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!nvidia-smi

Mon Sep 26 07:14:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
%cd "/content/drive/MyDrive/TrasformerCOD"

/content/drive/.shortcut-targets-by-id/1KuaPGsEIzClSGbQuEeWCzVFtXaJYpEHS/TrasformerCOD


In [4]:
# import socket
# hostname = socket.getfqdn(socket.gethostname(  ))
# print(hostname)

In [5]:
!pip install timm==0.4.5
!pip install opencv-python
!pip install tensorboard
!pip install tqdm
!pip install torch-scope
!pip install einops

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 287 kB 8.9 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 125 kB 9.1 MB/s 
     |████████████████████████████████| 57 kB 6.3 MB/s 
     |████████████████████████████████| 181 kB 70.4 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 4.0 MB 55.5 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
# !pip install torch==1.9.1

In [10]:
%cd /content/drive/MyDrive/TrasformerCOD

/content/drive/.shortcut-targets-by-id/1KuaPGsEIzClSGbQuEeWCzVFtXaJYpEHS/TrasformerCOD


In [ ]:
!python train.py --task 'COD'  --uncer_method ganabp

[INFO] Experiments saved in:  COD_2.5e-05_swin_basic_cat_ganabp_REMOVE
pretrained_dict:  ['__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'move_to_end', 'pop', 'popitem', 'setdefault', 'update', 'values']
[INFO]: Model based on [swin_basic_cat_ganabp] have 18.9461Mb paramerters in total
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that exce

In [11]:
#40 epoch
!python train.py --task 'COD'  --uncer_method ganabp --ckpt last

experiments/COD_2.5e-05_swin_basic_cat_ganabp_REMOVE/models
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from config import param as option
  File "/content/drive/.shortcut-targets-by-id/1KuaPGsEIzClSGbQuEeWCzVFtXaJYpEHS/TrasformerCOD/config.py", line 99, in <module>
    model_list = os.listdir(model_path)
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/COD_2.5e-05_swin_basic_cat_ganabp_REMOVE/models'


In [ ]:
#lần 2 28/6
#sota epoch 10
!python train.py --task=COD  --uncer_method ganabp --ckpt last # check point last


[INFO] Experiments saved in:  COD_2.5e-05_swin_basic_cat_ganabp_REMOVE
/usr/local/lib/python3.7/dist-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[INFO]: Model based on [swin_basic_cat_ganabp] have 87.3161Mb paramerters in total
Load checkpoint from experiments/COD_2.5e-05_swin_basic_cat_ganabp_REMOVE/models/20_0.459_generator.pth
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if nece

In [ ]:
#lần 3 28/6 bắt đầu từ epoch 1028-6, lr=1.25
#sota epoch 9
!python train.py --task=COD  --uncer_method ganabp --ckpt last

[INFO] Experiments saved in:  COD_1.25e-05_swin_basic_cat_ganabp_REMOVE
/usr/local/lib/python3.7/dist-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[INFO]: Model based on [swin_basic_cat_ganabp] have 87.3161Mb paramerters in total
Load checkpoint from experiments/COD_1.25e-05_swin_basic_cat_ganabp_REMOVE/models/10_0.406_generator.pth
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if ne

In [ ]:
#lần 3 29/6 bắt đầu từ epoch 8 29-6, lr=6.25e-06
#sota epoch
!python train.py --task=COD  --uncer_method ganabp --ckpt last
# ganabp : gan + abp / abp: thêm 1 lớp bias: là confident 

[INFO] Experiments saved in:  COD_6.25e-06_swin_basic_cat_ganabp_REMOVE
/usr/local/lib/python3.7/dist-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[INFO]: Model based on [swin_basic_cat_ganabp] have 87.3161Mb paramerters in total
Load checkpoint from experiments/COD_6.25e-06_swin_basic_cat_ganabp_REMOVE/models/08_0.362_generator.pth
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if ne

In [ ]:
#lần 4 29/6 bắt đầu từ epoch 14 29-6, lr=3.13e-06
#sota epoch
!python train.py --task=COD  --uncer_method ganabp --ckpt last

[INFO] Experiments saved in:  COD_3.13e-06_swin_basic_cat_ganabp_REMOVE
/usr/local/lib/python3.7/dist-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[INFO]: Model based on [swin_basic_cat_ganabp] have 87.3161Mb paramerters in total
Load checkpoint from experiments/COD_3.13e-06_swin_basic_cat_ganabp_REMOVE/models/14_0.344_generator.pth
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if ne

In [ ]:
# # eval
# !apt install octave 3.2.3


Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libghc-simple-reflect-dev-0.3.2-33624' for regex '3.2.3'
Note, selecting 'libghc-mime-mail-ses-dev-0.3.2.3-e7066' for regex '3.2.3'
Note, selecting 'libghc-pqueue-prof-1.3.2.3-6daeb' for regex '3.2.3'
Note, selecting 'libghc-mime-mail-ses-prof-0.3.2.3-e7066' for regex '3.2.3'
Note, selecting 'libghc-pqueue-dev-1.3.2.3-6daeb' for regex '3.2.3'
Note, selecting 'libghc-simple-reflect-prof-0.3.2-33624' for regex '3.2.3'
Note, selecting 'libghc-mime-mail-ses-dev' instead of 'libghc-mime-mail-ses-dev-0.3.2.3-e7066'
Note, selecting 'libghc-mime-mail-ses-prof' instead of 'libghc-mime-mail-ses-prof-0.3.2.3-e7066'
Note, selecting 'libghc-simple-reflect-dev' instead of 'libghc-simple-reflect-dev-0.3.2-33624'
Note, selecting 'libghc-simple-reflect-prof' instead of 'libghc-simple-reflect-prof-0.3.2-33624'
Note, selecting 'libghc-pqueue-dev' instead of 'libghc-pqueue-dev-1.3.2.3-6daeb'
No

In [ ]:
# %cd eval

/content/drive/MyDrive/TrasformerSOD/eval


In [ ]:
# !octave -W main.m

dataset = CVC-300
Processing 1/1: CVC-300 Dataset
model = PraNet
Evaluating(CVC-300 Dataset,PraNet Model, camourflage_00012.png Image): 1/250
error: 'mapminmax' undefined near line 89 column 30
error: called from
    main at line 89 column 20


In [ ]:
# !sudo su

bash: cannot set terminal process group (56): Inappropriate ioctl for device
bash: no job control in this shell
/content/drive/MyDrive/TrasformerSOD/eval# exit
exit


In [ ]:
import os
from PIL import Image
import numpy as np
image_root='./camo/Agoc/'
height = width = 64 ############https://stackoverflow.com/questions/55663880/how-to-use-featurewise-center-true-together-with-flow-from-directory-in-imagedat

# gt_root='/home/hoang/Desktop/luanvan/data/CAMO-V.1.0_CVIU2019-20220314T013357Z-001/gancam/train/GTBtrain/'
images = [image_root + f for f in os.listdir(image_root) if f.endswith('.jpg') or f.endswith('.png')] ####################################3.convert('L')    .convert('RGB') cv2.resize 
# gts = [gt_root + f for f in os.listdir(image_root) if f.endswith('.jpg') or f.endswith('.png')]# thay gt_root=image_root để lấy tên
images = sorted(images)
# gts=sorted(gts)
# for img_path in images:
#     img = Image.open(img_path)
x = np.array([np.array(Image.open(fname).convert('RGB').resize((width, height))) for fname in images])
import pickle
# pickle.dump( x, filehandle, protocol=2 )
x=np.stack(x, axis=0)
x.dump('Agoc.npy')
x = np.load('Agoc.npy',allow_pickle=True)
# x=x.astype(float)
x=x.astype(float)/255.0
# # # x = [np.array([1.0,2.0,3.0]), np.array([1.0,2.0,3.0])]
# # x=np.stack(x, axis=0)
# # # x=np.array(x)
# # x=x.astype(float)/255.0
print (x[0])

[[[0.26666667 0.30196078 0.21568627]
  [0.22352941 0.2627451  0.1254902 ]
  [0.23137255 0.27058824 0.12941176]
  ...
  [0.08627451 0.09411765 0.03529412]
  [0.08235294 0.08627451 0.03921569]
  [0.07058824 0.0745098  0.04313725]]

 [[0.18431373 0.25098039 0.10196078]
  [0.18823529 0.22745098 0.09019608]
  [0.21176471 0.24705882 0.12156863]
  ...
  [0.19215686 0.21568627 0.08235294]
  [0.16078431 0.18039216 0.07843137]
  [0.19215686 0.21568627 0.08627451]]

 [[0.15294118 0.25882353 0.03137255]
  [0.22352941 0.32941176 0.08235294]
  [0.27058824 0.4        0.11372549]
  ...
  [0.18039216 0.22352941 0.0627451 ]
  [0.14509804 0.18039216 0.05490196]
  [0.20392157 0.24705882 0.08235294]]

 ...

 [[0.15686275 0.20784314 0.08235294]
  [0.25490196 0.32156863 0.13333333]
  [0.17647059 0.21568627 0.09019608]
  ...
  [0.22352941 0.26666667 0.12156863]
  [0.3254902  0.37254902 0.18039216]
  [0.27058824 0.30196078 0.14901961]]

 [[0.19215686 0.27058824 0.12156863]
  [0.17647059 0.24313725 0.09019608]
